src/tweetme/tweetme/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tweet/',include('tweets.urls')),
    url(r'^api/tweet/',include('tweets.api.urls',namespace='tweet-api'))

]

if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

src/tweetme/tweets/api/urls.py
from django.conf.urls import url

from django.views.generic.base import RedirectView

from .views import (
    TweetListAPIView
    )

urlpatterns = [
    # url(r'^$', RedirectView.as_view(url="/")), 
    url(r'^$', TweetListAPIView.as_view(), name='list'), # /api/tweet/
    # url(r'^create/$', TweetCreateView.as_view(), name='create'), # /tweet/create/
    # url(r'^(?P<pk>\d+)/$', TweetDetailView.as_view(), name='detail'), # /tweet/1/
    # url(r'^(?P<pk>\d+)/update/$', TweetUpdateView.as_view(), name='update'), # /tweet/1/update/
    # url(r'^(?P<pk>\d+)/delete/$', TweetDeleteView.as_view(), name='delete'), # /tweet/1/delete/
]

src/tweetme/tweets/urls.py
from .views import  TweetCreateView, TweetDetailView, TweetListView, TweetUpdateView
from django.conf.urls import url

urlpatterns = [
    url(r'^$', TweetListView.as_view(), name="list"),
    url(r'^create/', TweetCreateView.as_view(), name="create"),
    url(r'^(?P<pk>\d+)/$', TweetDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/update/$', TweetUpdateView.as_view(), name='update'),
]

src/tweetme/accounts/models.py
from django.db import models

src/tweetme/tweets/models.py
from django.db import models
from django.conf import settings
from .validators import validate_content
# Create your models here.



class Tweets(models.Model):
    user        =   models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
    content     =   models.CharField(max_length=140, validators=[validate_content])
    updated     =   models.DateTimeField(auto_now=True)
    timestamp   =   models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)

    class Meta:
        verbose_name = "Tweet"
        verbose_name_plural = "Tweets"

    """ def clean(self,*args,**kwargs):
        content = self.content
        if content == "abc":
            raise ValidationError("Content cannot be abc")
        return super(Tweets,self).clean(*args,**kwargs) """

src/tweetme/tweets/forms.py
from django import forms

from .models import Tweets

class TweetModelForm(forms.ModelForm):
    class Meta:
        model = Tweets
        fields = [
            "user",
            "content"
        ]

    def clean_content(self, *args, **kwargs):
        content = self.cleaned_data.get("content")
        if content == "abc":
            raise forms.ValidationError("Cannot be ABC")
        return content

src/tweetme/accounts/views.py
from django.shortcuts import render

src/tweetme/tweetme/views.py
from django.shortcuts import render

def home(request):
    return render(request,"",{})

src/tweetme/tweets/api/views.py
from rest_framework import generics


from tweets.models import Tweet
from .serializers import TweetModelSerializer


class TweetListAPIView(generics.ListAPIView):
    serializer_class = TweetModelSerializer

    def get_queryset(self):
        return Tweet.objects.all()

src/tweetme/tweets/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms.utils import ErrorList
from .models import Tweets
from django.views.generic import ListView,DetailView, CreateView, UpdateView
from .forms import TweetModelForm
from .mixin import FormUserNeededList
# Create your views here.


class TweetCreateView(FormUserNeededList, CreateView):
    #queryset = Tweets.objects.all()
    template_name ='tweets/create_view_html'
    form_class = TweetModelForm
    success_url = "/tweet/create/"
    login_url = '/login/'

class TweetUpdateView(LoginRequiredMixin,UpdateView):
    queryset         =   Tweets.objects.all()
    form_class       =   TweetModelForm
    template_name    =   'tweet/update_view.html'
    success_url      =   '/tweet/'

class TweetDetailView(DetailView):
    queryset = Tweets.objects.all()

    def get_object(self):
        return Tweets.objects.get(id=1)

class TweetListView(ListView):
    queryset = Tweets.objects.all()


def tweet_detail_view(request, id=1):
    obj = Tweets.objects.get(id=id)
    context = {
        "object": obj
    }
    return render(request, "tweets/detail_view.html", context)

def tweet_list_view(request):
    queryset = Tweets.objects.all()
    for obj in queryset:
        print(obj.content)
    context = {
        "object_list": queryset
    }
    return render(request,"tweets/list_view.html", context)

src/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Custom styles for this template -->
  </head>

  <body>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        </body>
        </html>

src/tweetme/tweets/templates/tweets/create_view.html
{% extends "base.html" %}

{% block title %}Create Tweet | {{ block.super }}{% endblock title %}


{% block content %}
<div class='row'>
    <div class='col-sm-8 col-sm-offset-2'>
        <h1>Create Tweet</h1>
        {% include "tweets/form.html" with form=form btn_title='Tweet' %}
    </div>
</div>
{% endblock content %}

src/tweetme/tweets/templates/tweets/delete_confirm.html
{% extends "base.html" %}


{% block content %}




<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete the tweet "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>


{% endblock content %}

src/tweetme/tweets/templates/tweets/detail_view.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-1" style="background-color:red;">
        {{object.user}}
    </div>
</div>

src/tweetme/tweets/templates/tweets/form.html
{% load crispy_forms_tags %}
<form class='form' method='POST' action="{% if action_url %}{{ action_url }}{% endif %}">
   {% csrf_token %}
    {{ form|crispy }}
    <input class='btn btn-primary' type="submit" value="{{ btn_title }}" />
</form>

src/tweetme/tweets/templates/tweets/search_form.html
 <form class="navbar-form navbar-left" method='GET' action='{% url "tweet:list" %}'>
        <div class="form-group">
            <input class="form-control" type='text' name='q' placeholder='Your search' value='{{ request.GET.q }}'/>
            </div>
        <input class="btn btn-default" type='submit' value='Search'/>

</form>

src/tweetme/tweets/templates/tweets/tweet_detail.html
{% extends "base.html" %}


{% block content %}
<div class='row'>
    <div class='col-sm-3 col-xs-12' style='background-color:yellow;'>
        <h1>{{ object.user }} </h1>
    </div>
    <div class='col-sm-9 col-xs-12'>
         {{ object.content }}<br/>
            <br/>
        {{ object.timestamp|timesince }}
    </div>

</div>

{% endblock content %}

  







<div class='row'>
    <div class='col-lg-3 col-md-6 col-sm-3 col-xs-12' style='background-color:red;'>
        {{ object.user }}   
    </div>
    <div class='col-md-6' >
        {{ object.user }}   
    </div>
    <div class='col-xs-12' style='background-color:green;'>
        {{ object.user }}   
    </div>
    <div class='col-xs-12' style='background-color:blue;'>
        {{ object.user }}   
    </div>
</div>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<div class='row'>

    
      <div class='col-sm-1' style='background-color:red;'>
        {{ object.user }}   
    </div>
    <div class='col-sm-1' style='background-color:yellow;'>
        {{ object.user }}   
    </div>
    <div class='col-sm-1' style='background-color:green;'>
        {{ object.user }}   
    </div>

    <div class='col-sm-1' style='background-color:blue;'>
        {{ object.user }}   
    </div>
      <div class='col-sm-1' style='background-color:red;'>
        {{ object.user }}   
    </div>
    <div class='col-sm-1' style='background-color:yellow;'>
        {{ object.user }}   
    </div>
    <div class='col-sm-1' style='background-color:green;'>
        {{ object.user }}   
    </div>

    <div class='col-sm-1' style='background-color:blue;'>
        
    </div>

</div>

src/tweetme/tweets/templates/tweets/tweet_list.html
{% extends "base.html" %}

<style>
#tweet-container {

}
</style>

{% block script %}
<script>
$(document).ready(function(){
  console.log("working");

      
          
  $.ajax({
    url: "/api/tweet/",
    method: "GET",
    success: function(data){
      // console.log(data)
      $.each(data, function(key, value){
          var tweetKey = key;
          var tweetContent = value.content;
          var tweetUser = value.user;
          $("#tweet-container").append(
              "<div class=\"media\"><div class=\"media-body\">" + tweetContent + "<br/> via " + tweetUser.username + " | " + "<a href='#'>View</a>" + "</div></div><hr/>"
          )
      })
    },
    error: function(data){
      console.log("error")
      console.log(data)
    }
  })





});
</script>
{% endblock script %}



{% block content %}

   
    <div class='row'>
        <div class='col-sm-3 col-xs-12' style='background-color:red;'>
        <h1>{{ request.user }}</h1>
        </div>
        <div class='col-sm-9 '>
             {% if not request.GET.q %}
                <div class=''>
                    
                    {% include "tweets/form.html" with form=create_form action_url=create_url btn_title='Tweet' %}

                </div>
                <hr/>
            {% endif %}

            <div id='tweet-container'>


          </div>


        {% for object in object_list %}
            <div class="media">
                  <div class="media-left">
                    <a href="#">
                      {% if object.image %}
                        <img class="media-object" src="..." alt="...">
                     {% endif %}
                    </a>
                  </div>
                  <div class="media-body">
                    {{ object.content }}<br/>
                    via {{ object.user }} | {{ object.timestamp|timesince }} ago | <a href='{{ object.get_absolute_url }}'>View</a>
                  </div>
            </div>
            <hr/>
        {% empty %}
            {% if request.GET.q %}
             <p>No tweets found.</p>
            {% else %}
            <p>No tweets yet.</p>
            {% endif %}
        {% endfor %}

        </div>
    </div>

{% endblock content %}

src/tweetme/tweets/templates/tweets/update_view.html
{% extends "base.html" %}


{% block content %}

{% include "tweets/form.html" with form=form btn_title='Update' %}
{% endblock content %}